services:
  srun-mobile-banking-api:
    image: "srun-mobile-banking-api"
    build: .
    container_name: srun-mobile-banking-api
    ports:
      - 16850:8080
    volumes:
      - /home/srun/server-file:/file-server/
    networks:
      - srun-mobile-banking-net
    depends_on:
      - srun-mobile-banking-db

  srun-mobile-banking-db:
    image: postgres:16.3-bullseye
    container_name: srun-mobile-banking-db
    ports:
      - 4456:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: sbc11
      POSTGRES_DB: srun-mobile_banking_db
    volumes:
      - srun-mobile-banking-vol:/var/lib/postgresql/data
    networks:
      - srun-mobile-banking-net

volumes:
  srun-mobile-banking-vol:

networks:
  srun-mobile-banking-net:
    driver: bridge