services:
  mobile-banking-api:
    image: "mobile-banking-api"
    build: .
    container_name: mobile-banking-api
    ports:
      - 16850:8080
    volumes:
      - /Users/srunveng/Desktop/filestorage:/file-server/
    networks:
      - mobile-banking-net
    depends_on:
      - mobile-banking-db

  mobile-banking-db:
    image: postgres:16.3-bullseye
    container_name: mobile-banking-db
    ports:
      - 4456:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: sbc11
      POSTGRES_DB: mobile_banking_db
    volumes:
      - mobile-banking-vol:/var/lib/postgresql/data
    networks:
      - mobile-banking-net

volumes:
  mobile-banking-vol:

networks:
  mobile-banking-net:
